export const aplicacion = "Agencia de viajes los 3 mosqueteros";
export const h1Home = "Inicio";
export const h1Clientes = "Gestión de clientes";
export const h1Mayoristas = "Gestión de mayoristas";
export const h1Viajes = "Gestión de viajes";
export const h1Ventas = "Gestión de ventas";
export const h1Usuarios = "Gestión de empleados"
export const h1Login = "Inicio de sesión";
export const h1Catalogo = "Catálogo de viajes";
export const h1Menu = "Menú principal";
export const tituloHome = h1Home + " - " + aplicacion;
export const tituloClientes = h1Clientes + " - " + aplicacion;
export const tituloMayoristas = h1Mayoristas + " - " + aplicacion;
export const tituloViajes = h1Viajes + " - " + aplicacion;
export const tituloVentas = h1Ventas + " - " + aplicacion;
export const tituloUsuarios = h1Usuarios + " - " + aplicacion;
export const tituloLogin = h1Login + " - " + aplicacion;
export const tituloCatalogo = h1Catalogo + " - " + aplicacion;
export const tituloMenu = h1Menu + " - " + aplicacion;